global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:1936']  # HAProxy admin interface

  - job_name: 'pgbouncer'
    static_configs:
      - targets: ['pgbouncer:6432']  # PgBouncer metrikleri

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
