global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'pgbouncer'
    static_configs:
      - targets: ['pgbouncer_exporter:9127']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy_exporter:9101']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'spring-web-api'
    metrics_path: '/actuator/prometheus'  # Spring Boot Prometheus metrikleri burada yayınlıyor
    static_configs:
      - targets: ['spring-web-api:8080']
